apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: {{ .Release.Namespace }}
  name: csr-agent-clusterrole
rules:
  - apiGroups: ["networking.zephyr.solo.io"]
    resources: ["meshgroups"]
    verbs: ["*"]
  - apiGroups: ["security.zephyr.solo.io"]
    resources: ["meshgroupcertificatesigningrequests", "meshgroupcertificatesigningrequests/status"]
    verbs: ["*"]
  - apiGroups: ["discovery.zephyr.solo.io"]
    resources: ["meshes"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["*"]
