steps:
# Setup SSH
# These are required before dep
- name: gcr.io/cloud-builders/gcloud
  args:
  - kms
  - decrypt
  - --ciphertext-file=ci/id_rsa.enc
  - --plaintext-file=/root/.ssh/id_rsa
  - --location=global
  - --keyring=build
  - --key=build-key
  volumes:
  - name: 'ssh'
    path: /root/.ssh
  id: 'get-ssh-key'
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    chmod 600 /root/.ssh/id_rsa
    cat <<EOF >/root/.ssh/config
    Hostname github.com
    IdentityFile /root/.ssh/id_rsa
    EOF
    mv ./ci/github_known_hosts /root/.ssh/known_hosts
    git config --global url."ssh://git@github.com/solo-io".insteadOf https://github.com/solo-io
  volumes:
  - name: 'ssh'
    path: /root/.ssh
  id: 'configure-git'

# Can create a dep cache by running 'gcloud builds submit . --config=cloudbuild-cache.yaml'
# These two steps should populate the cache
- name: gcr.io/cloud-builders/gsutil
  entrypoint: 'bash'
  args: ['-c', 'mkdir -p ./gopath/pkg/dep && gsutil cat gs://gloo-ee-cache/mesh-projects/mesh-projects-dep.tar.gz | tar -xzf -']
  id: 'download-untar-dep-cache'

# Run dep to set up the project so it can be built and tested
# Dep modifies workspace so that the code is moved into the PROJECT_ROOT
# All steps after this must set GOPATH
- name: 'gcr.io/$PROJECT_ID/dep:0.2.0'
  args: ['ensure']
  env:
  - 'PROJECT_ROOT=github.com/solo-io/mesh-projects'
  volumes:
  - name: 'ssh'
    path: /root/.ssh
  id: 'dep'
  waitFor: ['download-untar-dep-cache']

# Helm setup steps
- name: gcr.io/cloud-builders/gsutil
  entrypoint: mkdir
  args: ['-p', './_output/helm']
  dir: './gopath/src/github.com/solo-io/mesh-projects'
  waitFor: ['dep']
  id: 'make-helm-dir'
- name: 'gcr.io/$PROJECT_ID/go-make:0.2.0'
  args: ['fetch-helm']
  env:
  - 'PROJECT_ROOT=github.com/solo-io/mesh-projects'
  - 'GOPATH=/workspace/gopath'
  - 'TAGGED_VERSION=$TAG_NAME'
  dir: './gopath/src/github.com/solo-io/mesh-projects'
  id: 'fetch-helm'
  waitFor: ['dep']



- name: 'gcr.io/$PROJECT_ID/e2e-ginkgo:0.2.0'
  env:
  - 'PROJECT_ROOT=github.com/solo-io/mesh-projects'
  - 'GOPATH=/workspace/gopath'
  dir: './gopath/src/github.com/solo-io/mesh-projects'
  entrypoint: make
  args: ['check-format']
  waitFor: ['dep']
  id: 'check-format'

- name: 'gcr.io/$PROJECT_ID/go-make:0.2.0'
  entrypoint: 'bash'
  args: ['ci/check-code-and-docs-gen.sh']
  env:
  - 'PROJECT_ROOT=github.com/solo-io/mesh-projects'
  - 'GOPATH=/workspace/gopath'
  - 'TAGGED_VERSION=$TAG_NAME'
  dir: './gopath/src/github.com/solo-io/mesh-projects'
  volumes:
  - name: 'ssh'
    path: /root/.ssh
  waitFor: ['dep']
  id: 'check-code-and-docs-gen'

- name: 'gcr.io/$PROJECT_ID/go-make:0.2.0'
  args: ['docker']
  env:
  - 'PROJECT_ROOT=github.com/solo-io/mesh-projects'
  - 'GOPATH=/workspace/gopath'
  - 'TAGGED_VERSION=$TAG_NAME'
  - 'HELM_HOME=/root/.helm'
  dir: './gopath/src/github.com/solo-io/mesh-projects'
  volumes:
  - name: 'ssh'
    path: /root/.ssh
  id: 'make'

- name: 'gcr.io/$PROJECT_ID/e2e-ginkgo:0.2.0'
  args: ['-r', '-p']
  env:
  - 'PROJECT_ROOT=github.com/solo-io/mesh-projects'
  - 'GOPATH=/workspace/gopath'
  - 'TAGGED_VERSION=$TAG_NAME'
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=test-cluster'
  - 'HELM_HOME=/root/.helm'
  secretEnv: ["GITHUB_TOKEN"]
  dir: './gopath/src/github.com/solo-io/mesh-projects'
  volumes:
  - name: 'ssh'
    path: /root/.ssh
  waitFor: ['make']
  id: 'test'

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker login quay.io --username "solo-io+solobot" --password $$QUAY_IO_PASSWORD']
  secretEnv: ['QUAY_IO_PASSWORD']
  id: 'docker-login'
  waitFor: ['test']


- name: 'gcr.io/$PROJECT_ID/go-make:0.2.0'
  args: ['release']
  env:
  - 'PROJECT_ROOT=github.com/solo-io/mesh-projects'
  - 'GOPATH=/workspace/gopath'
  - 'TAGGED_VERSION=$TAG_NAME'
  - 'HELM_HOME=/root/.helm'
  dir: './gopath/src/github.com/solo-io/mesh-projects'
  volumes:
  - name: 'ssh'
    path: /root/.ssh
  waitFor: ['docker-login']
  secretEnv: ['GITHUB_TOKEN', 'QUAY_IO_PASSWORD']
  id: 'release'
# 2) Publish helm chart, compile manifests, produce release artifacts, deploy docs
# isolating this portion of the release in order to force the manifest to be regenerated with the tagged version
- name: 'gcr.io/$PROJECT_ID/go-make:0.2.0'
  args: ['manifest',  '-B']
  env:
  - 'DOCKER_CONFIG=/workspace/docker-config'
  - 'TAGGED_VERSION=$TAG_NAME'
  - 'PROJECT_ROOT=github.com/solo-io/mesh-projects'
  - 'GOPATH=/workspace/gopath'
  - 'HELM_HOME=/root/.helm' # tell helm where to find data
  dir: './gopath/src/github.com/solo-io/mesh-projects'
  volumes:
  - name: 'ssh'
    path: /root/.ssh
  id: 'release-chart'
# 3) Sync helm chart data back to google storage bucket
- name: 'gcr.io/$PROJECT_ID/go-make:0.2.0'
  args: ['save-helm']
  env:
  - 'PROJECT_ROOT=github.com/solo-io/mesh-projects'
  - 'GOPATH=/workspace/gopath'
  - 'TAGGED_VERSION=$TAG_NAME'
  dir: './gopath/src/github.com/solo-io/mesh-projects'
  id: 'save-helm-chart'

secrets:
- kmsKeyName: projects/gloo-ee/locations/global/keyRings/build/cryptoKeys/build-key
  secretEnv:
    GITHUB_TOKEN: CiQAwdWthrSJ1uI5Ao/LnmX8OzXmA5TNCtDpeV6JdNouaGh5vpwSUQD5SXFIkCBvnu/wYDSGwgWNJaQV75wP/kDephn5GGuGCe0EGFXXE54zyH8iHRL45Uq0s39SoHEyYoZXF2Qla8IbKGAKswPRViYSChPthQILdA==
    QUAY_IO_PASSWORD: CiQAwdWthifvdUjpVHAln3ZIz4WljWx6qLt8E4yJArmrU4/1HQoSaQD5SXFIeMulT7DxGdwW0L9R+gA0SATR05xpTz7JS9LXJK+4iYPlFvVPs7O3DYee2YPJoF7o44vJ94+AyuMLQucS6BhHXQ0t//GvQWaFvdcTO4qH5HYgGQSrRY0a4E3l+4q6/M4da2m98Q==
timeout: 1800s
tags: ['mesh-projects']
options:
  machineType: 'N1_HIGHCPU_32'
