[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/solo-io/gloo"
  version = "0.20.11"

[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "https://github.com/fsnotify/fsnotify.git"

[[constraint]]
  version = "1.3.0"
  name = "github.com/gogo/protobuf"

[[override]]
  name = "github.com/gogo/googleapis"
  version = "v1.0.0"

[[override]]
  version = "1.3.2"
  name = "github.com/golang/protobuf"

[[constraint]]
  name = "github.com/solo-io/solo-kit"
  version = "0.11.10"

[[constraint]]
  name = "github.com/solo-io/go-utils"
  version = "0.10.21"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.5.0"


[[override]]
  version = "v1.5.2"
  name = "github.com/russross/blackfriday"


[[override]]
  version = "=v0.8.2"
  name = "github.com/envoyproxy/go-control-plane"

# make sure all kubernetes code is the same version.
# when updating, update all in the same time.

[[override]]
  name = "k8s.io/kubernetes"
  version = "=v1.13.2"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.13.2"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.13.2"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.13.2"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.13.2"

[[override]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.13.2"

[[override]]
  name = "k8s.io/helm"
  version = "=v2.12.3"

[[override]]
  name = "github.com/go-openapi/spec"
  version = "0.19.2"

[[override]]
  name = "k8s.io/klog"
  revision = "9cbb78b20423182f9e5b2a214dd255f5e117d2d1"
  source = "github.com/stefanprodan/klog"