apiVersion: v2
description: mesh-group Helm chart for Kubernetes
name: mesh-group
version: %version%
home: https://solo.io
icon: ""
sources:
  - https://github.com/solo-io/mesh-projects
keywords:
  - kubernetes
  - istio
  - mesh
  - servicemesh
  - servicemeshhub
