kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mesh-networking-clusterrole-binding
  labels:
    app: service-mesh-hub
    service-mesh-hub: mesh-networking
subjects:
  - kind: ServiceAccount
    name: mesh-networking
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: mesh-networking-clusterrole
  apiGroup: rbac.authorization.k8s.io
