kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mesh-networking-role-binding
  labels:
    app: service-mesh-hub
    service-mesh-hub: mesh-networking
subjects:
  - kind: ServiceAccount
    name: mesh-networking
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: mesh-networking-role
  apiGroup: rbac.authorization.k8s.io
