apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: meshbridges.zephyr.solo.io
  annotations:
    "helm.sh/hook": crd-install
  labels:
    app: mesh-projects
spec:
  group: zephyr.solo.io
  names:
    kind: MeshBridge
    listKind: MeshBridgeList
    plural: meshbridges
    shortNames:
    - mb
  scope: Namespaced
  version: v1
  versions:
  - name: v1
    served: true
    storage: true

---

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: meshes.zephyr.solo.io
  annotations:
    "helm.sh/hook": crd-install
  labels:
    app: mesh-projects
spec:
  group: zephyr.solo.io
  names:
    kind: Mesh
    listKind: MeshList
    plural: meshes
    shortNames:
    - m
  scope: Namespaced
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
---

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: meshingresses.zephyr.solo.io
  annotations:
    "helm.sh/hook": crd-install
  labels:
    app: mesh-projects
spec:
  group: zephyr.solo.io
  names:
    kind: MeshIngress
    listKind: MeshIngressList
    plural: meshingresses
    shortNames:
    - mi
  scope: Namespaced
  version: v1
  versions:
  - name: v1
    served: true
    storage: true