{{- if .Values.global.crds.create }}

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: meshbridges.zephyr.solo.io
  annotations:
    "helm.sh/hook": crd-install
  labels:
    app: mesh-projects
spec:
  group: zephyr.solo.io
  names:
    kind: MeshBridge
    listKind: MeshBridgeList
    plural: meshbridges
    shortNames:
    - mb
  scope: Namespaced
  version: v1
  versions:
  - name: v1
    served: true
    storage: true

---

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: meshes.zephyr.solo.io
  annotations:
    "helm.sh/hook": crd-install
  labels:
    app: mesh-projects
spec:
  group: zephyr.solo.io
  names:
    kind: Mesh
    listKind: MeshList
    plural: meshes
    shortNames:
    - m
  scope: Namespaced
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
---

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: meshgroups.zephyr.solo.io
  annotations:
    "helm.sh/hook": crd-install
  labels:
    app: mesh-projects
spec:
  group: zephyr.solo.io
  names:
    kind: MeshGroup
    listKind: MeshGroupList
    plural: meshgroups
    shortNames:
    - mg
  scope: Namespaced
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
---

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: meshingresses.zephyr.solo.io
  annotations:
    "helm.sh/hook": crd-install
  labels:
    app: mesh-projects
spec:
  group: zephyr.solo.io
  names:
    kind: MeshIngress
    listKind: MeshIngressList
    plural: meshingresses
    shortNames:
    - mi
  scope: Namespaced
  version: v1
  versions:
  - name: v1
    served: true
    storage: true

---

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: settings.gloo.solo.io
  annotations:
    "helm.sh/hook": crd-install
  labels:
    gloo: settings
spec:
  group: gloo.solo.io
  names:
    kind: Settings
    listKind: SettingsList
    plural: settings
    shortNames:
      - st
  scope: Namespaced
  version: v1
  versions:
    - name: v1
      served: true
      storage: true

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: upstreams.gloo.solo.io
  annotations:
    "helm.sh/hook": crd-install
spec:
  group: gloo.solo.io
  names:
    kind: Upstream
    listKind: UpstreamList
    plural: upstreams
    shortNames:
      - us
    singular: upstream
  scope: Namespaced
  version: v1
  versions:
    - name: v1
      served: true
      storage: true
{{- end}}