{{- if not .Values.meshDiscovery.disabled }}
{{- $image := .Values.meshDiscovery.deployment.image }}
{{- if .Values.global  }}
{{- $image = merge .Values.meshDiscovery.deployment.image .Values.global.image }}
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sm-marketplace
    sm-marketplace: mc-mesh-discovery
  name: mc-mesh-discovery
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.meshDiscovery.deployment.replicas }}
  selector:
    matchLabels:
      sm-marketplace: mc-mesh-discovery
  template:
    metadata:
      labels:
        sm-marketplace: mc-mesh-discovery
      {{- if .Values.meshDiscovery.deployment.stats }}
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "9091"
        prometheus.io/scrape: "true"
      {{- end}}
    spec:
      serviceAccountName: mc-mesh-discovery
      volumes:
        - name: aws-cred
          secret:
            secretName: aws-cred
            optional: true
        - name: gcloud-cred
          secret:
            secretName: gcloud-cred
            optional: true
      containers:
      - image: {{template "gloo.image" $image}}
        imagePullPolicy: {{ $image.pullPolicy }}
        name: mc-mesh-discovery
        volumeMounts:
        ## If using EKS, create a secret called "aws-cred" in the .Release.Namespace namespace
        ## and include the following key-value pair:
        ## "credentials": <base64-encoded aws credentials, as can be gotten from: cat ~/.aws/credentials | base64>
          - mountPath: "/root/.aws/"
            name: aws-cred
            readOnly: true
        ## If using gcloud, create a secret called "gcloud-cred" in the .Release.Namespace namespace
        ## and include the following key-value pair:
        ## "credentials": <base64-encoded gcloud creds>
          - mountPath: "/root/.gcloud/"
            name: gcloud-cred
            readOnly: true
{{- if .Values.meshDiscovery.deployment.resources }}
        resources:
{{ toYaml .Values.meshDiscovery.deployment.resources | indent 10}}
{{- end}}
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: "/root/.gcloud/credentials"
        {{- if .Values.meshDiscovery.deployment.stats }}
          - name: START_STATS_SERVER
            value: "true"
        {{- end}}
{{- end }}
