{{- if not .Values.discovery.disabled }}
{{- $image := .Values.discovery.deployment.image }}
{{- if .Values.global  }}
{{- $image = merge .Values.discovery.deployment.image .Values.global.image }}
{{- end }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: sm-marketplace
    sm-marketplace: discovery
  name: discovery
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      sm-marketplace: discovery
  template:
    metadata:
      labels:
        sm-marketplace: discovery
        {{- if .Values.discovery.deployment.stats }}
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "9091"
        prometheus.io/scrape: "true"
      {{- end}}
    spec:
      serviceAccountName: discovery
      containers:
        - image: {{template "gloo.image" $image}}
          imagePullPolicy: {{ .Values.discovery.deployment.image.pullPolicy }}
          name: discovery
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          {{- if .Values.discovery.deployment.stats }}
            - name: START_STATS_SERVER
              value: "true"
          {{- end}}
{{- end}}