{{- if .Values.global.rbac.create}}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: discovery-role-binding
  labels:
    app: sm-marketplace
    sm-marketplace: discovery
subjects:
  - kind: ServiceAccount
    name: discovery
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
{{- end }}