
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: sm-marketplace
    sm-marketplace: mesh-config
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "5"
  name: mesh-config
  namespace: {{ $.Release.Namespace }}
---
{{- if .Values.global.rbac.create}}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mesh-config-role-binding
  labels:
    app: sm-marketplace
    sm-marketplace: mesh-config
subjects:
  - kind: ServiceAccount
    name: mesh-config
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
  {{- end }}
---
{{- if not .Values.meshConfig.disabled }}
{{- $image := .Values.meshConfig.deployment.image }}
{{- if .Values.global  }}
{{- $image = merge .Values.meshConfig.deployment.image .Values.global.image }}
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sm-marketplace
    sm-marketplace: mesh-config
  name: mesh-config
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.meshConfig.deployment.replicas }}
  selector:
    matchLabels:
      sm-marketplace: mesh-config
  template:
    metadata:
      labels:
        sm-marketplace: mesh-config
      {{- if .Values.meshConfig.deployment.stats }}
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "9091"
        prometheus.io/scrape: "true"
      {{- end}}
    spec:
      serviceAccountName: mesh-config
      volumes:
        - name: aws-cred
          secret:
            secretName: aws-cred
      containers:
      - image: {{template "gloo.image" $image}}
        imagePullPolicy: {{ $image.pullPolicy }}
        name: mesh-config
        ## If using EKS, create a secret called "aws-cred" in the .Release.Namespace namespace
        ## and include the following key-value pair:
        ## "credentials": <base64-encoded aws credentials, as can be gotten from: cat ~/.aws/credentials | base64>
        volumeMounts:
          - mountPath: "/root/.aws/"
            name: aws-cred
            readOnly: true
{{- if .Values.meshConfig.deployment.resources }}
        resources:
{{ toYaml .Values.meshConfig.deployment.resources | indent 10}}
{{- end}}
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        {{- if .Values.meshConfig.deployment.stats }}
          - name: START_STATS_SERVER
            value: "true"
        {{- end}}
{{- end }}
