# This secret is needed in order for its dependant pods to start
# If you want to connect to AWS services, you will need to replace the placeholder with valid credentials.
# The credentials must be base64 encoded, ex: `cat ~/.aws/credentials | base64`
apiVersion: v1
kind: Secret
metadata:
  name: aws-cred
  namespace: {{ $.Release.Namespace }}
data:
  credentials: xxxxxxxxxThisIsAPlaceholderPleaseReplaceWithValidCredentialsxxxxxxxx