apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    helm.sh/hook: crd-install
  labels:
    app: service-mesh-hub
    app.kubernetes.io/name: service-mesh-hub
  name: trafficpolicies.config.zephyr.solo.io
spec:
  group: config.zephyr.solo.io
  names:
    kind: TrafficPolicy
    listKind: TrafficPolicyList
    plural: trafficpolicies
    singular: trafficpolicy
  scope: Namespaced
  subresources:
    status: {}
  versions:
  - name: v1alpha1
    served: true
    storage: true

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    helm.sh/hook: crd-install
  labels:
    app: service-mesh-hub
    app.kubernetes.io/name: service-mesh-hub
  name: accesscontrolpolicies.config.zephyr.solo.io
spec:
  group: config.zephyr.solo.io
  names:
    kind: AccessControlPolicy
    listKind: AccessControlPolicyList
    plural: accesscontrolpolicies
    singular: accesscontrolpolicy
  scope: Namespaced
  subresources:
    status: {}
  versions:
  - name: v1alpha1
    served: true
    storage: true

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    helm.sh/hook: crd-install
  labels:
    app: service-mesh-hub
    app.kubernetes.io/name: service-mesh-hub
  name: meshgroups.config.zephyr.solo.io
spec:
  group: config.zephyr.solo.io
  names:
    kind: MeshGroup
    listKind: MeshGroupList
    plural: meshgroups
    singular: meshgroup
  scope: Namespaced
  subresources:
    status: {}
  versions:
  - name: v1alpha1
    served: true
    storage: true
