name: Release

on:
  release:
    types:
      - prereleased

jobs:
  publish-artifacts:
    name: Publish Artifacts
    runs-on: ubuntu-18.04
    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Set Release Tag
        run: |
          echo $GITHUB_REF
          echo ::set-env name=TAGGED_VERSION::${GITHUB_REF#refs/*/}

      - name: Upload Release Assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make upload-github-release-assets

      - name: Push Docker Images
        run: |
          echo ${{ secrets.CI_ADMIN_DOCKER_HUB_PASSWORD }} | docker login -u soloiobot --password-stdin
          make push-all-images

      - name: Set Up GCP Credentials
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          export_default_credentials: true
      - name: Publish Helm Charts
        run: |
          make publish-chart
